db.createUser({
  user: "myuser",
  pwd: "mypassword",
  roles: [
    {
      role: "readWrite",
      db: "mydatabase",
    },
  ],
});

db["status-codes"].insertMany([
  { code: "100", receivedBy: [] },
  { code: "101", receivedBy: [] },
  { code: "102", receivedBy: [] },
  { code: "200", receivedBy: [] },
  { code: "201", receivedBy: [] },
  { code: "202", receivedBy: [] },
  { code: "203", receivedBy: [] },
  { code: "204", receivedBy: [] },
  { code: "205", receivedBy: [] },
  { code: "206", receivedBy: [] },
  { code: "207", receivedBy: [] },
  { code: "208", receivedBy: [] },
  { code: "226", receivedBy: [] },
  { code: "300", receivedBy: [] },
  { code: "301", receivedBy: [] },
  { code: "302", receivedBy: [] },
  { code: "303", receivedBy: [] },
  { code: "304", receivedBy: [] },
  { code: "305", receivedBy: [] },
  { code: "306", receivedBy: [] },
  { code: "307", receivedBy: [] },
  { code: "308", receivedBy: [] },
  { code: "400", receivedBy: [] },
  { code: "401", receivedBy: [] },
  { code: "402", receivedBy: [] },
  { code: "403", receivedBy: [] },
  { code: "404", receivedBy: [] },
  { code: "405", receivedBy: [] },
  { code: "406", receivedBy: [] },
  { code: "407", receivedBy: [] },
  { code: "408", receivedBy: [] },
  { code: "409", receivedBy: [] },
  { code: "410", receivedBy: [] },
  { code: "411", receivedBy: [] },
  { code: "412", receivedBy: [] },
  { code: "413", receivedBy: [] },
  { code: "414", receivedBy: [] },
  { code: "415", receivedBy: [] },
  { code: "416", receivedBy: [] },
  { code: "417", receivedBy: [] },
  { code: "418", receivedBy: [] },
  { code: "422", receivedBy: [] },
  { code: "423", receivedBy: [] },
  { code: "424", receivedBy: [] },
  { code: "426", receivedBy: [] },
  { code: "428", receivedBy: [] },
  { code: "429", receivedBy: [] },
  { code: "431", receivedBy: [] },
  { code: "500", receivedBy: [] },
  { code: "501", receivedBy: [] },
  { code: "502", receivedBy: [] },
  { code: "503", receivedBy: [] },
  { code: "504", receivedBy: [] },
  { code: "505", receivedBy: [] },
  { code: "506", receivedBy: [] },
  { code: "507", receivedBy: [] },
  { code: "508", receivedBy: [] },
  { code: "510", receivedBy: [] },
  { code: "511", receivedBy: [] },
]);
